# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

project_name: logalize

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - id: binary
    format: binary
    files:
    - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ tolower .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: binary-tar-zst
    format: tar.zst
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ tolower .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

nfpms:
  - package_name: logalize
    homepage: "https://github.com/deponian/logalize"
    maintainer: "Rufus Deponian <rufus@deponian.com>"
    description: |
      Fast and extensible log colorizer.
      Alternative to ccze
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
    provides:
    - logalize
    section: "utils"
    priority: "optional"
    contents:
      - src: ./.logalize.yaml
        dst: /etc/{{ .ProjectName }}/logalize.yaml
        type: config

      - src: ./readme.md
        dst: /usr/share/doc/{{ .ProjectName }}/README

      - src: ./CHANGELOG.md
        dst: /usr/share/doc/{{ .ProjectName }}/CHANGELOG

      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/LICENSE
        packager: deb

      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/LICENSE
        packager: rpm

      - src: ./LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE
        packager: archlinux
    rpm:
      compression: zstd
    deb:
      compression: zstd
    archlinux:
      packager: Rufus Deponian <rufus@deponian.com>
