# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: logalize

env_files:
  github_token: ~/.github_token

before:
  hooks:
    - make VERSION={{ .Version }} manpage
    - make completions

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.date={{ printf "%.10s" .CommitDate }}

archives:
  - id: binary
    format: binary
    files:
    - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ tolower .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: binary-tar-zst
    format: tar.zst
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ tolower .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
      - "^ci:"

nfpms:
  - package_name: logalize
    homepage: "https://github.com/deponian/logalize"
    maintainer: "Rufus Deponian <rufus@deponian.com>"
    description: |
      Fast and extensible log colorizer.
      Alternative to ccze
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
    provides:
    - logalize
    section: "utils"
    priority: "optional"
    file_name_template: >-
      {{ .PackageName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    contents:
      - src: ./.logalize.yaml
        dst: /etc/{{ .ProjectName }}/logalize.yaml
        type: config
        file_info:
          mode: 0644

      - src: ./readme.md
        dst: /usr/share/doc/{{ .ProjectName }}/README
        file_info:
          mode: 0644

      - src: ./CHANGELOG.md
        dst: /usr/share/doc/{{ .ProjectName }}/CHANGELOG
        file_info:
          mode: 0644

      - src: ./manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644

      - src: ./completions/logalize.bash
        dst: /usr/share/bash-completion/completions/logalize
        file_info:
          mode: 0644
      - src: ./completions/logalize.fish
        dst: /usr/share/fish/vendor_completions.d/logalize.fish
        file_info:
          mode: 0644
      - src: ./completions/logalize.zsh
        dst: /usr/share/zsh/vendor-completions/_logalize
        packager: deb
        file_info:
          mode: 0644
      - src: ./completions/logalize.zsh
        dst: /usr/share/zsh/vendor-completions/_logalize
        packager: rpm
        file_info:
          mode: 0644
      - src: ./completions/logalize.zsh
        dst: /usr/share/zsh/site-functions/_logalize
        packager: archlinux
        file_info:
          mode: 0644

      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/LICENSE
        packager: deb
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/LICENSE
        packager: rpm
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/licenses/{{ .ProjectName }}/LICENSE
        packager: archlinux
        file_info:
          mode: 0644
    rpm:
      compression: zstd
    deb:
      compression: zstd
    archlinux:
      packager: Rufus Deponian <rufus@deponian.com>
