# formats:
#   # $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"
#   nginx-combined:
#     # $remote_addr
#     - pattern: (\d{1,3}(\.\d{1,3}){3} )
#       fg: "#f5ce42"
#     # -
#     - pattern: (- )
#       fg: "#807e7a"
#     # $remote_user
#     - pattern: ([^ ]+ )
#       fg: "#764a9e"
#     # [$time_local]
#     - pattern: (\[.+\] )
#       fg: "#148dd9"
#     # "$request"
#     - pattern: ("[^"]+" )
#       fg: "#9ddb56"
#     # $status
#     - pattern: (\d\d\d )
#       fg: "#ffffff"
#       alternatives:
#         - pattern: (2\d\d )
#           fg: "#00ff00"
#           style: bold
#         - pattern: (3\d\d )
#           fg: "#00ffff"
#           style: bold
#         - pattern: (4\d\d )
#           fg: "#ff0000"
#           style: bold
#         - pattern: (5\d\d )
#           fg: "#ff00ff"
#           style: bold
#     # $body_bytes_sent
#     - pattern: ([\d]+ )
#       fg: "#7d7d7d"
#     # "$http_referer"
#     - pattern: ("[^"]+" )
#       fg: "#3ae1f0"
#     # "$http_user_agent"
#     - pattern: ("[^"]+")
#       fg: "#aa7dd1"

# patterns:
#   string:
#     priority: 500
#     pattern: ("[^"]+"|'[^']+')
#     fg: "#00ff00"

#   number:
#     pattern: (\d+)
#     fg: "#00ffff"
#     style: bold

#   http-status-code:
#     pattern: (\d\d\d)
#     fg: "#ffffff"
#     alternatives:
#       - pattern: (2\d\d)
#         fg: "#00ff00"
#       - pattern: (3\d\d)
#         fg: "#00ffff"
#       - pattern: (4\d\d)
#         fg: "#ff0000"
#       - pattern: (5\d\d)
#         fg: "#ff00ff"

#   ipv4-address:
#     pattern: (\d{1,3}(\.\d{1,3}){3})
#     fg: "#ff0000"
#     bg: "#ffff00"

# words:
#   warning:
#     fg: "#fcba03"
#     style: bold
#     list:
#       - "ignore"
#       - "miss"
#       - "readonly"
#       - "reload"
#       - "skip"
#       - "warn"
#       - "restart"
