# This is an example configutaion file.
# Values below are not the default setting.
# If you want to get built-in defaults run "logalize --print-config"

# settings:
#   theme: "utopia"
#
#   no-builtin-formats: false
#   no-builtin-patterns: false
#   no-builtin-words: false
#   no-builtins: true
#
#   only-formats: false
#   only-patterns: false
#   only-words: false
#
#   no-ansi-escape-sequences-stripping: false
#
# formats:
#   nginx-combined:
#     - regexp: (\d{1,3}(?:\.\d{1,3}){3} )
#       name: remote-addr
#     - regexp: (- )
#       name: dash
#     - regexp: ([^ ]+ )
#       name: remote-user
#     - regexp: (\[.+\] )
#       name: time-local
#     - regexp: ("[^"]+" )
#       name: request
#     - regexp: (\d\d\d )
#       name: status
#       alternatives:
#         - regexp: (2\d\d )
#           name: 2xx
#         - regexp: (3\d\d )
#           name: 3xx
#         - regexp: (4\d\d )
#           name: 4xx
#         - regexp: (5\d\d )
#           name: 5xx
#     - regexp: ([\d]+ )
#       name: body-bytes-sent
#     - regexp: ("[^"]+" )
#       name: http-referer
#     - regexp: ("[^"]+")
#       name: http-user-agent
#
# patterns:
#   string:
#     priority: 500
#     regexp: ("[^"]+"|'[^']+')
#
#   number:
#     regexp: (\d+)
#
#   ipv4-address:
#     regexp: (\d{1,3}(\.\d{1,3}){3})
#
#   http-status:
#     regexp: (\d\d\d)
#     alternatives:
#       - regexp: (2\d\d)
#         name: 2xx
#       - regexp: (3\d\d)
#         name: 3xx
#       - regexp: (4\d\d)
#         name: 4xx
#       - regexp: (5\d\d)
#         name: 5xx
#
#   http-status-code:
#     priority: 100
#     regexps:
#       - regexp: (code:)
#         name: code
#       - regexp: ( \d\d\d)
#         name: status
#         alternatives:
#           - regexp: ( 2\d\d)
#             name: 2xx
#           - regexp: ( 3\d\d)
#             name: 3xx
#           - regexp: ( 4\d\d)
#             name: 4xx
#           - regexp: ( 5\d\d)
#             name: 5xx
#
# words:
#   warning:
#     - "ignore"
#     - "miss"
#     - "readonly"
#     - "reload"
#     - "skip"
#     - "warn"
#     - "restart"
#
# themes:
#   utopia:
#     formats:
#       nginx-combined:
#         remote-addr:
#           fg: "#ffc777"
#         dash:
#           fg: "#828bb8"
#         remote-user:
#           fg: "#4fd6be"
#         time-local:
#           fg: "#c099ff"
#         request:
#           fg: "#c3e88d"
#         status:
#           2xx:
#             fg: "#00ff00"
#             style: bold
#           3xx:
#             fg: "#00ffff"
#             style: bold
#           4xx:
#             fg: "#ff0000"
#             style: bold
#           5xx:
#             fg: "#ff00ff"
#             style: bold
#         body-bytes-sent:
#           fg: "#636da6"
#         http-referer:
#           fg: "#fca7ea"
#         http-user-agent:
#           link-to: remote-user
#
#     patterns:
#       string:
#         fg: "#00ff00"
#
#       number:
#         bg: "#00ffff"
#         style: bold
#
#       ipv4-address:
#         fg: "#ffc777"
#
#       http-status:
#         default:
#           fg: "#ffffff"
#         2xx:
#           fg: "#00ff00"
#         3xx:
#           fg: "#00ffff"
#         4xx:
#           fg: "#ff0000"
#         5xx:
#           fg: "#ff00ff"
#
#       http-status-code:
#         code:
#           fg: "#ffffff"
#         status:
#           default:
#             fg: "#ffffff"
#           2xx:
#             fg: "#00ff00"
#           3xx:
#             fg: "#00ffff"
#           4xx:
#             fg: "#ff0000"
#           5xx:
#             fg: "#ff00ff"
#
#     words:
#       warning:
#         fg: "#fcba03"
#         style: bold
