# INFO:
# Ingress Nginx default format
#
# SOURCE:
# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/
#
# SCHEME:
# $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id

formats:
  nginx-ingress-controller:
    # $remote_addr
    - regexp: (\d{1,3}(?:\.\d{1,3}){3} )
      name: remote-addr
    # -
    - regexp: (- )
      name: dash
    # $remote_user
    - regexp: ([^ ]+ )
      name: remote-user
    # [$time_local]
    - regexp: (\[.+\] )
      name: time-local
    # "$request"
    - regexp: ("[^"]+" )
      name: request
    # $status
    - regexp: (\d\d\d )
      name: status
      alternatives:
        - regexp: (2\d\d )
          name: 2xx
        - regexp: (3\d\d )
          name: 3xx
        - regexp: (4\d\d )
          name: 4xx
        - regexp: (5\d\d )
          name: 5xx
    # $body_bytes_sent
    - regexp: ([\d]+ )
      name: body-bytes-sent
    # "$http_referer"
    - regexp: ("[^"]+" )
      name: http-referer
    # "$http_user_agent"
    - regexp: ("[^"]+" )
      name: http-user-agent
    # $request_length
    - regexp: (\d+ )
      name: request-length
    # $request_time
    - regexp: ([\d\.]+ )
      name: request-time
    # [$proxy_upstream_name]
    - regexp: (\[.*\] )
      name: proxy-upstream-name
    # [$proxy_alternative_upstream_name]
    - regexp: (\[.*\] )
      name: proxy-alternative-upstream-name
    # $upstream_addr
    - regexp: ((?:\d{1,3}(\.\d{1,3}){3}:\d+|-) )
      name: upstream-addr
    # $upstream_response_length
    - regexp: ((?:\d+|-) )
      name: upstream-response-length
    # $upstream_response_time
    - regexp: ((?:[\d\.]+|-) )
      name: upstream-response-time
    # $upstream_status
    - regexp: ((?:\d\d\d|-) )
      name: upstream-status
      alternatives:
        - regexp: (2\d\d )
          name: 2xx
        - regexp: (3\d\d )
          name: 3xx
        - regexp: (4\d\d )
          name: 4xx
        - regexp: (5\d\d )
          name: 5xx
    # $req_id
    - regexp: ([[:xdigit:]]{32})
      name: req-id
