name: "Spell Check"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  typos:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, 'docs:') }}
    steps:
    - uses: actions/checkout@v4
    - uses: crate-ci/typos@v1.20.1
